language: php

php:
  - 7.2
  - 7.3
  - 7.4
  - nightly

env:
  global:
    - DEFAULT=1

matrix:
  include:
    - php: 7.4
      env: CHECKS=1 DEFAULT=0

  allow_failures:
    - php: nightly

install:
  - |
    if [[ $TRAVIS_PHP_VERSION == 'nightly' ]]; then
      composer install --no-interaction --ignore-platform-reqs
    else
      composer install --no-interaction
    fi

script:
  - if [[ $DEFAULT == 1 ]]; then vendor/bin/phpunit; fi

  - if [[ $CHECKS == 1 ]]; then composer stan-setup && composer stan; fi

notifications:
  email: false
